const CATEGORIES = {
  sport:     { label: 'Sport',       emoji: '🏆', color: '#E8753A', textColor: '#1C1008', bg: '#FFF3EC' },
  histoire:  { label: 'Histoire',    emoji: '📜', color: '#C4923A', textColor: '#1C1000', bg: '#FFF8EC' },
  geo:       { label: 'Géographie',  emoji: '🌍', color: '#4E9E72', textColor: '#081C10', bg: '#EDFAF3' },
  science:   { label: 'Science',     emoji: '🔬', color: '#4A8FD4', textColor: '#08101C', bg: '#EEF5FF' },
  art:       { label: 'Art & Lettres', emoji: '🎨', color: '#8E6BB8', textColor: '#100818', bg: '#F5F0FF' },
  cinema:    { label: 'Cinéma',      emoji: '🎬', color: '#C84B5A', textColor: '#1C0809', bg: '#FFF0F1' },
  culinaire: { label: 'Culinaire',   emoji: '🍽️', color: '#D4A83A', textColor: '#1C1400', bg: '#FFFBEE' },
  musique:   { label: 'Musique',     emoji: '🎵', color: '#C4637A', textColor: '#1C0810', bg: '#FFF0F4' },
};

const QUESTIONS = [
  // ── SPORT ──────────────────────────────────────────────────────────────────
  { id: 1,  cat: 'sport', q: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", a: "15 joueurs", exp: "Le chiffre XV dans le nom du sport fait directement référence au nombre de joueurs par équipe. Le rugby à 7 est la version olympique.", diff: 1 },
  { id: 2,  cat: 'sport', q: "Dans quel pays les Jeux Olympiques modernes ont-ils été fondés ?", a: "En Grèce (Athènes, 1896)", exp: "Pierre de Coubertin relance les Jeux Olympiques modernes à Athènes en 1896, s'inspirant des Jeux antiques de l'Olympie grecque.", diff: 1 },
  { id: 3,  cat: 'sport', q: "Quel pays a remporté le plus de Coupes du Monde de football ?", a: "Le Brésil (5 titres)", exp: "Le Brésil est le seul pays à avoir participé à toutes les Coupes du Monde : 1958, 1962, 1970, 1994 et 2002.", diff: 1 },
  { id: 4,  cat: 'sport', q: "Qui détient le record du monde du 100 mètres masculin ?", a: "Usain Bolt — 9,58 s (Berlin, 2009)", exp: "Bolt détient aussi les records du 200m (19,19 s) et du 4×100m avec la Jamaïque.", diff: 1 },
  { id: 5,  cat: 'sport', q: "En quelle année la France a-t-elle remporté la Coupe du Monde de football pour la première fois ?", a: "1998", exp: "La France bat le Brésil 3-0 en finale à Saint-Denis. Zidane marque un doublé, Petit clôt le score.", diff: 1 },
  { id: 6,  cat: 'sport', q: "Combien de sets faut-il gagner pour remporter un match à Wimbledon (hommes) ?", a: "3 sets gagnants (sur 5 possibles)", exp: "Les femmes jouent en 2 sets gagnants. Wimbledon est le seul Grand Chelem sur gazon.", diff: 2 },
  { id: 7,  cat: 'sport', q: "Quel nageur américain détient le record du plus grand nombre de médailles olympiques ?", a: "Michael Phelps — 28 médailles (23 en or)", exp: "Phelps a participé à 5 JO (2000-2016) et n'a jamais fini hors du podium en finale individuelle.", diff: 2 },
  { id: 8,  cat: 'sport', q: "Dans quel sport pratique-t-on le 'smash', le 'lob' et le 'passing-shot' ?", a: "Le tennis", exp: "Ces termes techniques du tennis décrivent respectivement une frappe en puissance vers le bas, un lift lobé par-dessus l'adversaire au filet, et un tir passant.", diff: 1 },

  // ── HISTOIRE (événements marquants — format musée avec photo) ────────────────
  { id: 9, cat: 'histoire', mode: 'event', diff: 1,
    event: "Les Pyramides de Gizeh", era: "ANTIQUITÉ", place: "Gizeh, Égypte", type: "Architecture",
    markTop: "−2560", markBot: "−2510", img: "assets/histoire/pyramides-gizeh.jpg",
    exp: "Érigées vers 2560 av. J.-C. pour les pharaons Khéops, Khéphren et Mykérinos, les pyramides de Gizeh sont les seules des Sept Merveilles du monde antique encore debout. Haute de 146 m, la grande pyramide est restée la plus haute construction humaine pendant près de 4 000 ans." },

  { id: 10, cat: 'histoire', mode: 'event', diff: 1,
    event: "Le Colisée de Rome", era: "ANTIQUITÉ", place: "Rome, Italie", type: "Empire romain",
    markTop: "72", markBot: "80", img: "assets/histoire/colisee-rome.jpg",
    exp: "Inauguré en l'an 80 sous l'empereur Titus, le Colisée pouvait accueillir jusqu'à 50 000 spectateurs venus assister aux combats de gladiateurs et aux jeux. Symbole de la puissance de Rome, il demeure le plus grand amphithéâtre jamais construit." },

  { id: 11, cat: 'histoire', mode: 'event', diff: 2,
    event: "La Grande Muraille de Chine", era: "ANTIQUITÉ", place: "Chine du Nord", type: "Fortification",
    markTop: "−220", markBot: "1644", img: "assets/histoire/grande-muraille.jpg",
    exp: "Commencée vers 220 av. J.-C. sous l'empereur Qin Shi Huang puis prolongée pendant près de deux millénaires, la Grande Muraille s'étend sur plus de 21 000 km. Elle protégeait l'empire chinois des invasions nomades venues du nord." },

  { id: 12, cat: 'histoire', mode: 'event', diff: 2,
    event: "La Peste noire", era: "MOYEN ÂGE", place: "Europe", type: "Pandémie",
    markTop: "1347", markBot: "1352", img: "assets/histoire/peste-noire.jpg",
    exp: "Entre 1347 et 1352, la peste noire ravage l'Europe et emporte entre 30 et 50 % de la population, soit environ 25 millions de morts. Transmise par les puces des rats à bord des navires marchands, elle bouleversa durablement la société médiévale." },

  { id: 13, cat: 'histoire', mode: 'event', diff: 2,
    event: "L'invention de l'imprimerie", era: "RENAISSANCE", place: "Mayence, Saint-Empire", type: "Invention",
    markTop: "1450", markBot: "1455", img: "assets/histoire/imprimerie.jpg",
    exp: "Vers 1450, Johannes Gutenberg met au point l'imprimerie à caractères mobiles en métal. Sa Bible, achevée vers 1455, est le premier grand livre imprimé d'Occident. L'invention démocratise le savoir et accélère la Réforme et la Renaissance." },

  { id: 14, cat: 'histoire', mode: 'event', diff: 1,
    event: "Colomb atteint l'Amérique", era: "RENAISSANCE", place: "Bahamas", type: "Exploration",
    markTop: "1492", markBot: "", img: "assets/histoire/colomb-amerique.jpg",
    exp: "Le 12 octobre 1492, Christophe Colomb, financé par les rois d'Espagne, atteint une île des Caraïbes en cherchant une route vers les Indes par l'ouest. Sa découverte ouvre l'ère des grandes explorations et la colonisation européenne du Nouveau Monde." },

  { id: 15, cat: 'histoire', mode: 'event', diff: 1,
    event: "La Révolution française", era: "RÉVOLUTION", place: "France", type: "Révolution",
    markTop: "1789", markBot: "1799", img: "assets/histoire/bastille.jpg",
    exp: "Le 14 juillet 1789, le peuple de Paris prend la Bastille, prison royale symbole de l'absolutisme. C'est le début de la Révolution française, qui abolit la monarchie, proclame la Déclaration des droits de l'homme et bouleverse l'ordre politique de toute l'Europe." },

  { id: 16, cat: 'histoire', mode: 'event', diff: 2,
    event: "L'Indépendance américaine", era: "XVIIIᵉ S.", place: "Philadelphie, É.-U.", type: "Indépendance",
    markTop: "1776", markBot: "1783", img: "assets/histoire/independance-usa.jpg",
    exp: "Le 4 juillet 1776, treize colonies britanniques d'Amérique proclament leur indépendance dans une déclaration rédigée par Thomas Jefferson. Reconnue en 1783, elle donne naissance aux États-Unis et inspire les révolutions démocratiques du monde entier." },

  { id: 104, cat: 'histoire', mode: 'event', diff: 2,
    event: "Le Sacre de Napoléon", era: "EMPIRE", place: "Paris, France", type: "Empire",
    markTop: "1804", markBot: "1815", img: "assets/histoire/sacre-napoleon.jpg",
    exp: "Le 2 décembre 1804, Napoléon Bonaparte se couronne lui-même empereur des Français dans la cathédrale Notre-Dame, sous le regard du pape Pie VII. Son règne réorganise l'Europe par les guerres et le Code civil, avant de s'achever à Waterloo en 1815." },

  { id: 105, cat: 'histoire', mode: 'event', diff: 1,
    event: "La Première Guerre mondiale", era: "XXᵉ SIÈCLE", place: "Europe", type: "Guerre",
    markTop: "1914", markBot: "1918", img: "assets/histoire/premiere-gm.jpg",
    exp: "De 1914 à 1918, la Grande Guerre oppose les puissances européennes dans des combats d'une violence inédite, marqués par la guerre de tranchées. Elle fait près de 10 millions de morts et redessine la carte du monde par le traité de Versailles en 1919." },

  { id: 106, cat: 'histoire', mode: 'event', diff: 2,
    event: "La Révolution russe", era: "XXᵉ SIÈCLE", place: "Petrograd, Russie", type: "Révolution",
    markTop: "1917", markBot: "", img: "assets/histoire/revolution-russe.jpg",
    exp: "En octobre 1917, les bolcheviks de Lénine s'emparent du pouvoir à Petrograd lors de la prise du Palais d'Hiver. La Révolution russe renverse le tsarisme et fonde le premier État communiste, l'URSS, qui marquera tout le XXᵉ siècle." },

  { id: 107, cat: 'histoire', mode: 'event', diff: 1,
    event: "La Seconde Guerre mondiale", era: "XXᵉ SIÈCLE", place: "Monde", type: "Guerre",
    markTop: "1939", markBot: "1945", img: "assets/histoire/seconde-gm.jpg",
    exp: "De 1939 à 1945, le conflit le plus meurtrier de l'histoire oppose les Alliés aux forces de l'Axe. Avec environ 60 millions de morts, la Shoah et l'arme atomique, il bouleverse l'ordre mondial. Le débarquement de Normandie, en juin 1944, marque le tournant en Europe." },

  { id: 108, cat: 'histoire', mode: 'event', diff: 2,
    event: "La bombe d'Hiroshima", era: "XXᵉ SIÈCLE", place: "Hiroshima, Japon", type: "Arme nucléaire",
    markTop: "1945", markBot: "", img: "assets/histoire/hiroshima.jpg",
    exp: "Le 6 août 1945, les États-Unis larguent la première bombe atomique de l'histoire sur Hiroshima, suivie de Nagasaki trois jours plus tard. Faisant plus de 200 000 morts, ces bombardements précipitent la capitulation du Japon et ouvrent l'ère nucléaire." },

  { id: 109, cat: 'histoire', mode: 'event', diff: 1,
    event: "Le premier pas sur la Lune", era: "ESPACE", place: "Mer de la Tranquillité", type: "Exploit spatial",
    markTop: "1969", markBot: "", img: "assets/histoire/lune-apollo11.jpg",
    exp: "Le 21 juillet 1969, l'Américain Neil Armstrong devient le premier homme à marcher sur la Lune lors de la mission Apollo 11 : « un petit pas pour l'homme, un bond de géant pour l'humanité ». Plus de 500 millions de personnes suivent l'événement en direct à la télévision." },

  { id: 110, cat: 'histoire', mode: 'event', diff: 1,
    event: "La chute du mur de Berlin", era: "GUERRE FROIDE", place: "Berlin, Allemagne", type: "Géopolitique",
    markTop: "1961", markBot: "1989", img: "assets/histoire/mur-berlin.jpg",
    exp: "Dans la nuit du 9 novembre 1989, après 28 ans de séparation, les Berlinois abattent le mur qui divisait leur ville et symbolisait le rideau de fer. Sa chute annonce la fin de la guerre froide et la réunification de l'Allemagne, scellée en 1990." },

  { id: 111, cat: 'histoire', mode: 'event', diff: 1,
    event: "Les attentats du 11 septembre", era: "XXIᵉ SIÈCLE", place: "New York, É.-U.", type: "Terrorisme",
    markTop: "2001", markBot: "", img: "assets/histoire/11-septembre.jpg",
    exp: "Le 11 septembre 2001, des terroristes d'Al-Qaïda détournent quatre avions et frappent les tours jumelles du World Trade Center et le Pentagone, faisant près de 3 000 morts. Ces attentats bouleversent la géopolitique mondiale et déclenchent la « guerre contre le terrorisme »." },

  // ── GÉOGRAPHIE ─────────────────────────────────────────────────────────────
  { id: 17, cat: 'geo', q: "Quel est le plus long fleuve du monde ?", a: "Le Nil (6 650 km)", exp: "Selon la majorité des sources, le Nil est le plus long. Certaines études récentes mettent l'Amazone en tête selon le point de source retenu.", diff: 2 },
  { id: 18, cat: 'geo', q: "Quelle est la capitale du Canada ?", a: "Ottawa", exp: "Ottawa est la capitale fédérale depuis 1857, choisie par la reine Victoria comme compromis entre Toronto (anglophone) et Montréal (francophone).", diff: 2 },
  { id: 19, cat: 'geo', q: "Quel est le plus grand pays du monde en superficie ?", a: "La Russie (17,1 millions de km²)", exp: "La Russie couvre plus de 11 % des terres émergées et s'étend sur 11 fuseaux horaires, soit presque deux fois la superficie du Canada.", diff: 1 },
  { id: 20, cat: 'geo', q: "Quel est le plus haut sommet du monde ?", a: "L'Everest (8 849 m)", exp: "Situé dans l'Himalaya entre le Népal et le Tibet, l'Everest a été gravi pour la première fois le 29 mai 1953 par Edmund Hillary et Tenzing Norgay.", diff: 1 },
  { id: 21, cat: 'geo', q: "Dans quel océan se trouve Madagascar ?", a: "L'océan Indien", exp: "Madagascar est la 4e plus grande île du monde, à 400 km de la côte mozambicaine. Sa faune est unique : 90 % des espèces y sont endémiques.", diff: 2 },
  { id: 22, cat: 'geo', q: "Quelle est la monnaie officielle du Japon ?", a: "Le yen (¥)", exp: "Introduit en 1871 pour moderniser le système monétaire japonais, le yen est l'une des trois devises les plus échangées au monde avec le dollar et l'euro.", diff: 1 },
  { id: 23, cat: 'geo', q: "Combien de pays partagent une frontière avec la France métropolitaine ?", a: "8 pays", exp: "Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco, Andorre et Espagne. La France a la plus grande diversité de voisins en Europe de l'Ouest.", diff: 2 },
  { id: 24, cat: 'geo', q: "Quel détroit sépare l'Europe de l'Afrique ?", a: "Le détroit de Gibraltar (14 km au minimum)", exp: "Seulement 14 km séparent l'Espagne du Maroc au point le plus étroit. Le détroit relie l'Atlantique à la Méditerranée.", diff: 2 },

  // ── SCIENCE ────────────────────────────────────────────────────────────────
  { id: 25, cat: 'science', q: "Quelle est la formule chimique de l'eau ?", a: "H₂O", exp: "L'eau est composée de deux atomes d'hydrogène et d'un atome d'oxygène. Cette molécule polaire est indispensable à toute vie connue.", diff: 1 },
  { id: 26, cat: 'science', q: "Qui a développé la théorie de la relativité générale ?", a: "Albert Einstein (1915)", exp: "La relativité générale décrit la gravitation comme une courbure de l'espace-temps. Elle prédit les trous noirs, les ondes gravitationnelles et la dilatation du temps.", diff: 1 },
  { id: 27, cat: 'science', q: "Combien d'os possède le corps humain adulte ?", a: "206 os", exp: "À la naissance on en compte ~270, mais certains fusionnent. Le plus petit est l'étrier dans l'oreille (3 mm) ; le plus grand est le fémur.", diff: 2 },
  { id: 28, cat: 'science', q: "Quelle planète est surnommée la 'planète rouge' ?", a: "Mars", exp: "Mars doit sa couleur rouge à l'oxyde de fer (rouille) en surface. C'est la planète la plus susceptible d'être habitée par des humains dans le futur.", diff: 1 },
  { id: 29, cat: 'science', q: "À quelle vitesse se déplace la lumière dans le vide ?", a: "≈ 300 000 km/s (exactement 299 792 458 m/s)", exp: "C'est la vitesse maximale de l'univers. À cette vitesse, la lumière parcourt la distance Terre-Lune en 1,3 seconde et fait le tour de la Terre en 0,13 s.", diff: 2 },
  { id: 30, cat: 'science', q: "Quel élément chimique est le plus abondant dans l'univers ?", a: "L'hydrogène (H)", exp: "L'hydrogène représente ~75 % de la matière baryonique de l'univers. Il est le carburant principal des étoiles via la fusion nucléaire.", diff: 2 },
  { id: 31, cat: 'science', q: "Qu'est-ce que la photosynthèse ?", a: "La conversion de lumière + CO₂ + eau en glucose + oxygène par les plantes", exp: "La photosynthèse se déroule dans les chloroplastes. Elle est à la base de presque toutes les chaînes alimentaires terrestres.", diff: 1 },
  { id: 32, cat: 'science', q: "Quel est le symbole chimique de l'or ?", a: "Au (du latin Aurum)", exp: "L'or (numéro atomique 79) est un métal noble très conducteur, résistant à l'oxydation. Un gramme d'or peut être étiré en un fil de 165 mètres.", diff: 2 },

  // ── ART (peinture — format ticket avec œuvre) ───────────────────────────────
  { id: 33, cat: 'art', title: "La Joconde", artist: "Léonard de Vinci", year: "1503", diff: 1,
    img: "assets/art/joconde.jpg",
    exp: "Vers 1503. Le tableau le plus visité au monde, exposé au Louvre. Son sourire énigmatique et la technique du sfumato en font une icône absolue." },
  { id: 34, cat: 'art', title: "La Nuit étoilée", artist: "Vincent van Gogh", year: "1889", diff: 1,
    img: "assets/art/nuit-etoilee.jpg",
    exp: "Peinte en 1889 depuis sa chambre à l'asile de Saint-Rémy-de-Provence. Elle est aujourd'hui exposée au MoMA de New York." },
  { id: 35, cat: 'art', title: "Le Cri", artist: "Edvard Munch", year: "1893", diff: 1,
    img: "assets/art/le-cri.jpg",
    exp: "Réalisé en 1893, symbole universel de l'angoisse existentielle moderne. Munch en a peint quatre versions ; la plus célèbre est au Musée National d'Oslo." },
  { id: 36, cat: 'art', title: "La Jeune Fille à la perle", artist: "Johannes Vermeer", year: "1665", diff: 2,
    img: "assets/art/jeune-fille-perle.jpg",
    exp: "Vers 1665, surnommée la « Joconde du Nord ». Ce n'est pas un portrait mais une « tronie », une étude de visage. Conservée au Mauritshuis de La Haye." },
  { id: 37, cat: 'art', title: "La Grande Vague de Kanagawa", artist: "Katsushika Hokusai", year: "1831", diff: 2,
    img: "assets/art/grande-vague.jpg",
    exp: "Vers 1831, l'estampe japonaise (ukiyo-e) la plus célèbre. Une vague géante menace des barques devant le mont Fuji. Hokusai l'a réalisée à environ 70 ans." },
  { id: 38, cat: 'art', title: "La Naissance de Vénus", artist: "Sandro Botticelli", year: "1485", diff: 2,
    img: "assets/art/naissance-venus.jpg",
    exp: "Vers 1485, chef-d'œuvre de la Renaissance florentine. Vénus émerge des flots sur une coquille, soufflée vers le rivage par Zéphyr. Exposé aux Offices, à Florence." },
  { id: 39, cat: 'art', title: "La Liberté guidant le peuple", artist: "Eugène Delacroix", year: "1830", diff: 2,
    img: "assets/art/liberte.jpg",
    exp: "1830. Allégorie de la Liberté brandissant le drapeau tricolore sur des barricades, inspirée des Trois Glorieuses de juillet 1830. Conservée au Louvre." },
  { id: 40, cat: 'art', title: "Impression, soleil levant", artist: "Claude Monet", year: "1872", diff: 3,
    img: "assets/art/impression-soleil.jpg",
    exp: "1872. C'est cette toile qui a donné son nom à l'impressionnisme — terme d'abord employé de façon moqueuse par le critique Louis Leroy. Musée Marmottan, Paris." },
  { id: 41, cat: 'art', title: "Le Baiser", artist: "Gustav Klimt", year: "1908", diff: 2,
    img: "assets/art/le-baiser.jpg",
    exp: "1908, œuvre phare de la « période dorée » de Klimt, réalisée à la feuille d'or véritable. Symbole de l'Art nouveau viennois. Conservé au Belvédère, Vienne." },
  { id: 42, cat: 'art', title: "La Cène", artist: "Léonard de Vinci", year: "1495", diff: 2,
    img: "assets/art/la-cene.jpg",
    exp: "Vers 1495, peinture murale à Milan représentant le dernier repas du Christ avec ses apôtres. Célèbre pour sa composition en perspective et le visage de Judas." },
  { id: 43, cat: 'art', title: "Guernica", artist: "Pablo Picasso", year: "1937", diff: 2,
    img: "assets/art/guernica.jpg",
    exp: "1937. Œuvre monumentale (3,49 × 7,76 m) peinte en réponse au bombardement de la ville basque de Guernica par les nazis. Symbole universel de l'horreur de la guerre. Musée Reina Sofía, Madrid." },
  { id: 44, cat: 'art', title: "La Persistance de la mémoire", artist: "Salvador Dalí", year: "1931", diff: 2,
    img: "assets/art/montres-molles.jpg",
    exp: "1931, aussi appelée « Les Montres molles ». Huile sur toile (24 × 33 cm) peinte en quelques heures, dit Dalí, inspiré par la vision d'un camembert qui fond. MoMA, New York." },
  { id: 45, cat: 'art', title: "Les Demoiselles d'Avignon", artist: "Pablo Picasso", year: "1907", diff: 3,
    img: "assets/art/demoiselles-avignon.jpg",
    exp: "1907. Toile révolutionnaire qui brise toutes les conventions de la représentation du corps humain et pose les bases du cubisme. MoMA, New York." },
  { id: 46, cat: 'art', title: "Les Tournesols", artist: "Vincent van Gogh", year: "1888", diff: 1,
    img: "assets/art/tournesols.jpg",
    exp: "1888, série de 7 toiles peintes à Arles pour décorer la chambre de Gauguin. Symbole de l'amitié de Van Gogh. L'une d'elles a été vendue en 1987 pour 39,9 millions de dollars." },
  { id: 47, cat: 'art', title: "Les Époux Arnolfini", artist: "Jan van Eyck", year: "1434", diff: 3,
    img: "assets/art/arnolfini.jpg",
    exp: "1434. Portrait double mystérieux et extraordinairement détaillé de Giovanni di Nicolao Arnolfini et son épouse. Van Eyck se représente dans le miroir convexe en arrière-plan. National Gallery, Londres." },
  { id: 48, cat: 'art', title: "American Gothic", artist: "Grant Wood", year: "1930", diff: 2,
    img: "assets/art/american-gothic.jpg",
    exp: "1930. Icône de la peinture américaine représentant un fermier et sa fille (souvent pris pour mari et femme) devant une maison de style gothique charpentier. Art Institute of Chicago." },
  { id: 49, cat: 'art', title: "Saturne dévorant son fils", artist: "Francisco de Goya", year: "1823", diff: 3,
    img: "assets/art/saturne-goya.jpg",
    exp: "1823. L'une des 14 « Peintures noires » que Goya réalisa directement sur les murs de sa maison à la fin de sa vie. Scène terrifiante tirée de la mythologie : Saturne dévore ses enfants de peur d'être détrôné. Musée du Prado, Madrid." },
  { id: 50, cat: 'art', title: "L'École d'Athènes", artist: "Raphaël", year: "1511", diff: 3,
    img: "assets/art/ecole-athenes.jpg",
    exp: "1511. Fresque monumentale (770 cm de large) commandée par le pape Jules II pour ses appartements au Vatican. Elle réunit les plus grands philosophes de l'Antiquité : Platon (au centre) pointe vers le ciel, Aristote vers la terre. Musées du Vatican." },
  { id: 51, cat: 'art', title: "Le Radeau de la Méduse", artist: "Théodore Géricault", year: "1819", diff: 3,
    img: "assets/art/radeau-meduse.jpg",
    exp: "1819. Toile monumentale (5 × 7 m) inspirée du naufrage réel de la frégate Méduse en 1816, qui causa la mort de 147 personnes. Géricault a interviewé des survivants et peint des cadavres pour se documenter. Musée du Louvre." },
  { id: 52, cat: 'art', title: "Autoportrait au collier d'épines", artist: "Frida Kahlo", year: "1940", diff: 2,
    img: "assets/art/frida-kahlo.jpg",
    exp: "1940. L'une des œuvres les plus connues de Kahlo, peinte après son divorce d'avec Diego Rivera. Le colibri porte-bonheur, le chat noir et le singe renvoient à la symbolique mexicaine. University of Texas, Austin." },
  { id: 77, cat: 'art', title: "Les Glaneuses", artist: "Jean-François Millet", year: "1857", diff: 2,
    img: "assets/art/glaneuses.jpg",
    exp: "1857. Trois femmes ramassent les épis de blé laissés après la moisson — un travail réservé aux plus pauvres. Le tableau fut mal reçu à l'époque : les conservateurs craignaient une ode au socialisme paysan. Musée d'Orsay, Paris." },
  { id: 78, cat: 'art', title: "Olympia", artist: "Édouard Manet", year: "1863", diff: 3,
    img: "assets/art/olympia-manet.jpg",
    exp: "1863. Femme nue allongée, regardant le spectateur droit dans les yeux — scandale absolu au Salon de 1865. Manet s'inspire de la Vénus d'Urbin du Titien, mais remplace la déesse par une prostituée moderne. Musée d'Orsay, Paris." },
  { id: 79, cat: 'art', title: "La Ronde de nuit", artist: "Rembrandt van Rijn", year: "1642", diff: 2,
    img: "assets/art/ronde-nuit.jpg",
    exp: "1642. Chef-d'œuvre du baroque hollandais représentant une milice en marche, dont la composition dynamique et l'utilisation révolutionnaire de la lumière et de l'ombre sidérèrent les contemporains. Rijksmuseum, Amsterdam." },
  { id: 80, cat: 'art', title: "Les Nymphéas", artist: "Claude Monet", year: "1906", diff: 2,
    img: "assets/art/nympheas.jpg",
    exp: "1906. Série de 250 toiles peintes sur 30 ans dans le jardin de Giverny. Monet, atteint de cataractes, s'affranchit progressivement de la réalité pour aboutir à une abstraction quasi totale. Musée de l'Orangerie, Paris." },
  { id: 81, cat: 'art', title: "Les Meules", artist: "Claude Monet", year: "1890", diff: 2,
    img: "assets/art/meules-monet.jpg",
    exp: "1890. Série de 25 toiles représentant des meules de foin à Giverny sous différentes lumières et saisons — la première grande série de Monet dédiée à un même motif. Art Institute of Chicago." },
  { id: 82, cat: 'art', title: "Femme à l'ombrelle", artist: "Claude Monet", year: "1875", diff: 2,
    img: "assets/art/femme-ombrelle.jpg",
    exp: "1875. Portrait de Camille Monet et de leur fils Jean dans un champ. L'angle de vue plongeant et la touche impressionniste rapide saisissent l'instant et le vent — l'un des tableaux les plus populaires du mouvement. National Gallery of Art, Washington." },
  { id: 83, cat: 'art', title: "La Nuit étoilée sur le Rhône", artist: "Vincent van Gogh", year: "1888", diff: 3,
    img: "assets/art/nuit-rhone.jpg",
    exp: "1888. Peinte à Arles depuis les berges du Rhône, un an avant La Nuit étoilée de Saint-Rémy. Van Gogh y montre les étoiles se reflétant sur l'eau et les lumières de la ville — version plus apaisée de son obsession nocturne. Musée d'Orsay, Paris." },
  { id: 84, cat: 'art', title: "Autoportrait à l'oreille bandée", artist: "Vincent van Gogh", year: "1889", diff: 1,
    img: "assets/art/autoportrait-oreille.jpg",
    exp: "Janvier 1889, peint quelques semaines après que Van Gogh se soit tranché le lobe de l'oreille lors d'une crise après une dispute avec Gauguin. L'un de ses nombreux autoportraits — il en a peint plus de 35. Courtauld Gallery, Londres." },
  { id: 85, cat: 'art', title: "La Primavera", artist: "Sandro Botticelli", year: "1482", diff: 3,
    img: "assets/art/primavera.jpg",
    exp: "Vers 1482. Allégorie du Printemps représentant neuf figures mythologiques dont Vénus, les Trois Grâces et Mercure. L'une des peintures non religieuses les plus commentées de l'histoire de l'art. Galerie des Offices, Florence." },
  { id: 86, cat: 'art', title: "Les Joueurs de cartes", artist: "Paul Cézanne", year: "1895", diff: 3,
    img: "assets/art/joueurs-cartes.jpg",
    exp: "Vers 1894-95. Série de cinq versions représentant des paysans jouant aux cartes. La composition épurée, presque cubiste, a influencé Picasso et tout l'art moderne du XXe siècle. Musée d'Orsay, Paris." },
  { id: 87, cat: 'art', title: "La Montagne Sainte-Victoire", artist: "Paul Cézanne", year: "1904", diff: 3,
    img: "assets/art/montagne-victoire.jpg",
    exp: "Vers 1904. Cézanne a peint cette montagne près d'Aix-en-Provence plus de 80 fois tout au long de sa vie. Sa façon de structurer la nature en plans géométriques a directement inspiré le cubisme de Picasso et Braque." },
  { id: 88, cat: 'art', title: "Le Rêve", artist: "Henri Rousseau", year: "1910", diff: 3,
    img: "assets/art/songe-rousseau.jpg",
    exp: "1910, dernière grande toile de Rousseau avant sa mort. Une femme nue rêve au milieu d'une jungle foisonnante peuplée d'animaux exotiques et d'un joueur de flûte. Rousseau n'avait jamais quitté la France — il peignait ses jungles de mémoire, depuis les serres du Jardin des Plantes. MoMA, New York." },
  { id: 89, cat: 'art', title: "Le Déjeuner des canotiers", artist: "Pierre-Auguste Renoir", year: "1881", diff: 2,
    img: "assets/art/dejeuner-canotiers.jpg",
    exp: "1881. Scène de convivialité sur la terrasse du restaurant Fournaise à Chatou, représentant les amis de Renoir dont sa future femme Aline Charigot. L'une des grandes œuvres de l'impressionnisme tardif. The Phillips Collection, Washington." },

  { id: 92, cat: 'art', title: "Le Bal du moulin de la Galette", artist: "Pierre-Auguste Renoir", year: "1876", diff: 2,
    img: "assets/art/moulin-galette.jpg",
    exp: "1876. Scène de fête populaire à Montmartre, où bourgeois et ouvriers dansent ensemble sous les lampions. Chef-d'œuvre de l'impressionnisme : la lumière filtrée par les feuillages crée des taches dorées sur les visages. Musée d'Orsay, Paris." },

  { id: 93, cat: 'art', title: "Un dimanche après-midi à la Grande Jatte", artist: "Georges Seurat", year: "1886", diff: 2,
    img: "assets/art/grande-jatte.jpg",
    exp: "1886. Œuvre fondatrice du pointillisme : Seurat y applique sa théorie de la division des couleurs en points purs juxtaposés. Il a mis deux ans à peindre ces 48 personnages au bord de la Seine. Art Institute of Chicago." },

  { id: 94, cat: 'art', title: "La Grande Odalisque", artist: "Jean-Auguste-Dominique Ingres", year: "1814", diff: 3,
    img: "assets/art/odalisque.jpg",
    exp: "1814. Femme orientale allongée aux proportions anatomiquement impossible (deux vertèbres supplémentaires). La toile scandalisa les critiques au Salon de 1819 par son mélange de sensualité et de froideur néoclassique. Musée du Louvre, Paris." },

  { id: 95, cat: 'art', title: "La Laitière", artist: "Johannes Vermeer", year: "1658", diff: 2,
    img: "assets/art/laitiere-vermeer.jpg",
    exp: "Vers 1658. Servante versant du lait avec une concentration absolue — la lumière naturelle de gauche transforme ce geste banal en moment d'éternité. Tableau si célèbre aux Pays-Bas qu'on l'appelle familièrement « notre Joconde ». Rijksmuseum, Amsterdam." },

  { id: 96, cat: 'art', title: "La Création d'Adam", artist: "Michel-Ange", year: "1512", diff: 1,
    img: "assets/art/creation-adam.jpg",
    exp: "1512. Fragment central de la voûte de la Chapelle Sixtine. Dieu et Adam se tendent les mains sans se toucher — l'étincelle de vie dans cet espace vide est l'une des images les plus reproduites de l'humanité. Chapelle Sixtine, Vatican." },

  { id: 97, cat: 'art', title: "Las Meninas", artist: "Diego Velázquez", year: "1656", diff: 2,
    img: "assets/art/las-meninas.jpg",
    exp: "1656. Œuvre énigmatique où Velázquez se représente en train de peindre la famille royale — mais qui regardons-nous ? Un jeu de miroirs et de perspectives qui a fasciné Picasso, qui en a réalisé 58 variations. Musée du Prado, Madrid." },

  { id: 98, cat: 'art', title: "Nighthawks", artist: "Edward Hopper", year: "1942", diff: 2,
    img: "assets/art/nighthawks-hopper.jpg",
    exp: "1942. Quatre silhouettes isolées dans un diner américain au milieu de la nuit urbaine. L'absence de porte visible, la lumière crue et la solitude des personnages en font l'œuvre la plus représentative de l'isolement moderne. Art Institute of Chicago." },

  { id: 99, cat: 'art', title: "Le Déjeuner sur l'herbe", artist: "Édouard Manet", year: "1863", diff: 2,
    img: "assets/art/dejeuner-herbe.jpg",
    exp: "1863. Scandale au Salon des Refusés : une femme nue pique-nique tranquillement avec des hommes habillés. Napoléon III lui-même la qualifia de tableau indécent. Pourtant, c'est une réinterprétation d'une gravure de Raphaël. Musée d'Orsay, Paris." },

  { id: 100, cat: 'art', title: "Le Trois Mai 1808", artist: "Francisco de Goya", year: "1814", diff: 3,
    img: "assets/art/tres-mayo-goya.jpg",
    exp: "1814. Goya peint les exécutions de civils espagnols par les troupes napoléoniennes. L'homme en blanc aux bras levés devient un symbole universel du sacrifice. Tableau fondateur de la peinture de guerre moderne. Musée du Prado, Madrid." },

  { id: 101, cat: 'art', title: "La Chambre à Arles", artist: "Vincent van Gogh", year: "1888", diff: 2,
    img: "assets/art/chambre-arles.jpg",
    exp: "1888. Van Gogh a peint sa propre chambre à Arles — les couleurs vives et la perspective déformée reflètent son état d'esprit agité. Il en a réalisé trois versions. La simplicité voulue comme symbole du repos. Art Institute of Chicago." },

  { id: 102, cat: 'art', title: "Le Serment des Horaces", artist: "Jacques-Louis David", year: "1784", diff: 3,
    img: "assets/art/serment-horaces.jpg",
    exp: "1784. Trois frères romains prêtent serment de vaincre ou mourir pour Rome. David y incarne l'idéal néoclassique et les vertus républicaines — la toile fut perçue comme un appel révolutionnaire 5 ans avant 1789. Musée du Louvre, Paris." },

  { id: 103, cat: 'art', title: "La Balançoire", artist: "Jean-Honoré Fragonard", year: "1767", diff: 3,
    img: "assets/art/balancoire-fragonard.jpg",
    exp: "1767. Commandée par un baron libertin qui voulait se voir couché dans les buissons regardant sous la jupe d'une jeune femme. Fragonard transforme cette scène galante en chef-d'œuvre de légèreté rococo, toute en roses et dentelles. Wallace Collection, Londres." },

  // ── CINÉMA ─────────────────────────────────────────────────────────────────
  { id: 53, cat: 'cinema', q: "Quel film de Steven Spielberg est le plus rentable de sa carrière ?", a: "E.T. l'extra-terrestre (1982)", exp: "E.T. a tenu le record du film le plus rentable de l'histoire pendant 11 ans, avant d'être détrôné par Jurassic Park, puis Titanic.", diff: 2 },
  { id: 54, cat: 'cinema', q: "Qui a réalisé la trilogie 'Le Seigneur des Anneaux' ?", a: "Peter Jackson (2001–2003)", exp: "Le Retour du Roi remporte 11 Oscars dont Meilleur Film, égalant Ben-Hur et Titanic. La trilogie est tournée intégralement en Nouvelle-Zélande.", diff: 1 },
  { id: 55, cat: 'cinema', q: "Dans quel film entend-on la réplique 'Je suis ton père' ?", a: "L'Empire contre-attaque (1980)", exp: "C'est Darth Vader qui la dit à Luke Skywalker. La réplique originale en anglais est 'I am your father'. Elle est considérée comme le twist le plus célèbre du cinéma.", diff: 1 },
  { id: 56, cat: 'cinema', q: "Qui a joué le rôle de James Bond pour la première fois au cinéma ?", a: "Sean Connery (Dr. No, 1962)", exp: "Connery incarne Bond dans 7 films. La franchise est la plus longue de l'histoire du cinéma, avec plus de 60 ans de production.", diff: 2 },
  { id: 57, cat: 'cinema', q: "Quel studio d'animation a créé Toy Story, Cars et Up ?", a: "Pixar Animation Studios", exp: "Toy Story (1995) est le premier long-métrage entièrement en images de synthèse. Pixar a été acquis par Disney en 2006 pour 7,4 milliards de dollars.", diff: 1 },
  { id: 58, cat: 'cinema', q: "Quel film a remporté la Palme d'Or à Cannes en 2019 ?", a: "Parasite — Bong Joon-ho (Corée du Sud)", exp: "Parasite remporte ensuite 4 Oscars en 2020 dont Meilleur Film, devenant le premier film non anglophone à obtenir cette récompense suprême.", diff: 2 },
  { id: 59, cat: 'cinema', q: "Quel réalisateur est derrière 'Pulp Fiction', 'Kill Bill' et 'Django Unchained' ?", a: "Quentin Tarantino", exp: "Tarantino est célèbre pour ses dialogues ciselés, sa violence stylisée, ses structures non-linéaires et ses nombreuses références à la culture pop.", diff: 1 },
  { id: 60, cat: 'cinema', q: "Quel film de Stanley Kubrick se déroule dans un hôtel isolé sous la neige ?", a: "Shining (The Shining, 1980)", exp: "Adapté du roman de Stephen King, Shining met en scène Jack Nicholson dans le rôle d'un écrivain devenant fou dans l'Overlook Hotel. Le film est classé #1 des films d'horreur.", diff: 2 },

  // ── CULINAIRE ──────────────────────────────────────────────────────────────
  { id: 61, cat: 'culinaire', q: "De quel pays est originaire la pizza ?", a: "L'Italie (Naples)", exp: "La pizza moderne naît à Naples au XVIIIe siècle. La Margherita fut créée en 1889 pour la reine Marguerite de Savoie, avec les couleurs du drapeau italien.", diff: 1 },
  { id: 62, cat: 'culinaire', q: "Quel est l'ingrédient principal du guacamole ?", a: "L'avocat", exp: "Le guacamole vient de l'aztèque 'ahuacamolli' (sauce d'avocat). Il est agrémenté de citron vert, d'oignon, de coriandre et de piment au Mexique.", diff: 1 },
  { id: 63, cat: 'culinaire', q: "Quelle épice est la plus chère au monde au kilo ?", a: "Le safran (jusqu'à 30 000 €/kg)", exp: "Le safran provient des stigmates de la fleur Crocus sativus. Une seule fleur ne donne que 3 stigmates ; il en faut ~200 000 pour obtenir 500 g de safran.", diff: 2 },
  { id: 64, cat: 'culinaire', q: "De quel pays est originaire le sushi ?", a: "Le Japon", exp: "Le sushi existe sous forme de poisson fermenté dans du riz depuis le IXe siècle. Le nigiri-sushi actuel apparaît à Edo (Tokyo) au début du XIXe siècle.", diff: 1 },
  { id: 65, cat: 'culinaire', q: "Quel pays produit le plus de cacao au monde ?", a: "La Côte d'Ivoire (~45 % de la production mondiale)", exp: "La Côte d'Ivoire est suivie par le Ghana et l'Indonésie. L'Afrique de l'Ouest représente à elle seule 70 % de la production mondiale de cacao.", diff: 3 },
  { id: 66, cat: 'culinaire', q: "Comment appelle-t-on un steak à peine saisi, encore froid à l'intérieur ?", a: "Bleu", exp: "L'ordre de cuisson en France : bleu → saignant → à point → bien cuit. Un steak 'bleu' est juste saisi en surface, rouge et froid au centre.", diff: 1 },
  { id: 67, cat: 'culinaire', q: "Quelle est la différence principale entre un cappuccino et un latte ?", a: "Le ratio lait/mousse : le cappuccino a plus de mousse, le latte plus de lait", exp: "Cappuccino : 1/3 espresso, 1/3 lait chaud, 1/3 mousse (environ 180 ml). Latte : même base mais 3× plus de lait chaud et très peu de mousse (250-400 ml).", diff: 2 },
  { id: 68, cat: 'culinaire', q: "Qu'est-ce que la 'réaction de Maillard' en cuisine ?", a: "La réaction chimique entre acides aminés et sucres qui dore et parfume les aliments", exp: "Décrite par Louis-Camille Maillard en 1912, cette réaction est responsable du goût et de la couleur du pain grillé, de la viande saisie, du café torréfié…", diff: 3 },

  // ── MUSIQUE ────────────────────────────────────────────────────────────────
  { id: 69, cat: 'musique', mode: 'vinyl',
    song: "Bohemian Rhapsody", artist: "Queen", year: "1975", diff: 1, vinylColor: "#B71C1C",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/a4/17/20/a4172095-6812-79b6-1ba9-ae10b74ec2c7/mzaf_981426288313751423.plus.aac.p.m4a",
    exp: "Composée par Freddie Mercury, cette suite rock de 6 minutes brisait tous les codes. 9 semaines n°1 en UK, élue meilleure chanson de tous les temps par de nombreux classements." },

  { id: 70, cat: 'musique', mode: 'vinyl',
    song: "Billie Jean", artist: "Michael Jackson", year: "1982", diff: 1, vinylColor: "#0D47A1",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/dc/bc/8a/dcbc8a3e-4ce1-c00d-cc02-eda2212053c7/mzaf_8347559338388601510.plus.aac.p.m4a",
    exp: "Extrait de Thriller (1982), l'album le plus vendu de l'histoire. Michael Jackson a inventé le moonwalk lors de sa première performance de cette chanson à la télévision en 1983." },

  { id: 71, cat: 'musique', mode: 'vinyl',
    song: "Hotel California", artist: "Eagles", year: "1977", diff: 1, vinylColor: "#E65100",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/c7/95/a3/c795a34c-e485-29ce-7666-3bf69d208266/mzaf_16021391925102282319.plus.aac.p.m4a",
    exp: "Hymne des Eagles (1977), ses paroles mystérieuses décrivent un voyageur piégé dans un hôtel — métaphore du mode de vie des rock stars à Hollywood." },

  { id: 72, cat: 'musique', mode: 'vinyl',
    song: "La Vie en rose", artist: "Édith Piaf", year: "1946", diff: 1, vinylColor: "#880E4F",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/1e/e0/8d/1ee08da2-a8ea-0d4b-6d56-5db76f866dbf/mzaf_13978184747254142650.plus.aac.p.m4a",
    exp: "Composée par Édith Piaf en 1945 pour un amour perdu pendant la guerre, c'est l'une des chansons françaises les plus connues et les plus reprises au monde." },

  { id: 73, cat: 'musique', mode: 'vinyl',
    song: "Thriller", artist: "Michael Jackson", year: "1983", diff: 1, vinylColor: "#4A148C",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/58/8c/cb/588ccb9a-ab79-4a38-43b5-d4c24ea42859/mzaf_2083607504726567992.plus.aac.p.m4a",
    exp: "Le clip de Thriller (1983) réalisé par John Landis dure 14 minutes — le plus long et le plus cher de l'histoire. La danse des zombies est l'une des chorégraphies les plus imitées au monde." },

  { id: 74, cat: 'musique', mode: 'vinyl',
    song: "Stairway to Heaven", artist: "Led Zeppelin", year: "1971", diff: 2, vinylColor: "#1B5E20",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/60/61/5f/60615fd1-7425-78b3-21ab-fed7411a89ea/mzaf_7178841208140363975.plus.aac.p.m4a",
    exp: "Issue de Led Zeppelin IV (1971), cette chanson de 8 minutes passe du folk acoustique au hard rock. Robert Plant a écrit les paroles spontanément, assis au coin du feu en studio." },

  { id: 75, cat: 'musique', mode: 'vinyl',
    song: "Smells Like Teen Spirit", artist: "Nirvana", year: "1991", diff: 2, vinylColor: "#006064",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/a6/53/1e/a6531efa-397c-eb73-ecab-9b2790c1471e/mzaf_16440344883389407474.plus.aac.p.m4a",
    exp: "Premier single de Nevermind (1991), cette chanson a propulsé le grunge sur la scène mondiale et signé la fin de la domination du hair metal des années 80." },

  { id: 76, cat: 'musique', mode: 'vinyl',
    song: "Rolling in the Deep", artist: "Adele", year: "2010", diff: 1, vinylColor: "#4E342E",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/1f/aa/38/1faa38cc-3137-1409-ccb9-2eaf92a1b386/mzaf_5683578537884510102.plus.aac.p.m4a",
    exp: "Écrit après une rupture en seulement 10 minutes, ce premier single de l'album 21 a été enregistré en live en une seule prise, avec la batterie placée dans un couloir pour l'acoustique." },

  { id: 90, cat: 'musique', mode: 'vinyl',
    song: "Heroes", artist: "David Bowie", year: "1977", diff: 2, vinylColor: "#37474F",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/1f/f3/12/1ff3122a-eb3e-373d-d524-cfe00de9b19a/mzaf_8446634475827049231.plus.aac.p.m4a",
    exp: "Composée à Berlin en 1977 avec Brian Eno, Heroes s'inspire d'un couple aperçu s'embrassant au pied du Mur de Berlin. Bowie a enregistré les vocaux avec 3 micros à distances différentes." },

  { id: 91, cat: 'musique', mode: 'vinyl',
    song: "Get Lucky", artist: "Daft Punk", year: "2013", diff: 1, vinylColor: "#F57F17",
    preview: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/d4/d3/1e/d4d31eb4-7405-b806-8346-3c52ad5b4cf4/mzaf_8095545455942962509.plus.aac.p.m4a",
    exp: "Extrait de Random Access Memories (2013, 5 Grammy), produit avec Pharrell Williams et le guitariste Nile Rodgers, ce titre symbolise le retour à la musique jouée en live et a dominé les charts mondiaux." },
];
