const CATEGORIES = {
  sport:     { label: 'Sport',       emoji: '🏆', color: '#E8753A', textColor: '#1C1008', bg: '#FFF3EC' },
  histoire:  { label: 'Histoire',    emoji: '📜', color: '#C4923A', textColor: '#1C1000', bg: '#FFF8EC' },
  geo:       { label: 'Géographie',  emoji: '🌍', color: '#4E9E72', textColor: '#081C10', bg: '#EDFAF3' },
  science:   { label: 'Science',     emoji: '🔬', color: '#4A8FD4', textColor: '#08101C', bg: '#EEF5FF' },
  art:       { label: 'Art & Lettres', emoji: '🎨', color: '#8E6BB8', textColor: '#100818', bg: '#F5F0FF' },
  cinema:    { label: 'Cinéma',      emoji: '🎬', color: '#C84B5A', textColor: '#1C0809', bg: '#FFF0F1' },
  culinaire: { label: 'Culinaire',   emoji: '🍽️', color: '#D4A83A', textColor: '#1C1400', bg: '#FFFBEE' },
  musique:   { label: 'Musique',     emoji: '🎵', color: '#C4637A', textColor: '#1C0810', bg: '#FFF0F4' },
};

const QUESTIONS = [
  // ── SPORT ──────────────────────────────────────────────────────────────────
  { id: 1,  cat: 'sport', q: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", a: "15 joueurs", exp: "Le chiffre XV dans le nom du sport fait directement référence au nombre de joueurs par équipe. Le rugby à 7 est la version olympique.", diff: 1 },
  { id: 2,  cat: 'sport', q: "Dans quel pays les Jeux Olympiques modernes ont-ils été fondés ?", a: "En Grèce (Athènes, 1896)", exp: "Pierre de Coubertin relance les Jeux Olympiques modernes à Athènes en 1896, s'inspirant des Jeux antiques de l'Olympie grecque.", diff: 1 },
  { id: 3,  cat: 'sport', q: "Quel pays a remporté le plus de Coupes du Monde de football ?", a: "Le Brésil (5 titres)", exp: "Le Brésil est le seul pays à avoir participé à toutes les Coupes du Monde : 1958, 1962, 1970, 1994 et 2002.", diff: 1 },
  { id: 4,  cat: 'sport', q: "Qui détient le record du monde du 100 mètres masculin ?", a: "Usain Bolt — 9,58 s (Berlin, 2009)", exp: "Bolt détient aussi les records du 200m (19,19 s) et du 4×100m avec la Jamaïque.", diff: 1 },
  { id: 5,  cat: 'sport', q: "En quelle année la France a-t-elle remporté la Coupe du Monde de football pour la première fois ?", a: "1998", exp: "La France bat le Brésil 3-0 en finale à Saint-Denis. Zidane marque un doublé, Petit clôt le score.", diff: 1 },
  { id: 6,  cat: 'sport', q: "Combien de sets faut-il gagner pour remporter un match à Wimbledon (hommes) ?", a: "3 sets gagnants (sur 5 possibles)", exp: "Les femmes jouent en 2 sets gagnants. Wimbledon est le seul Grand Chelem sur gazon.", diff: 2 },
  { id: 7,  cat: 'sport', q: "Quel nageur américain détient le record du plus grand nombre de médailles olympiques ?", a: "Michael Phelps — 28 médailles (23 en or)", exp: "Phelps a participé à 5 JO (2000-2016) et n'a jamais fini hors du podium en finale individuelle.", diff: 2 },
  { id: 8,  cat: 'sport', q: "Dans quel sport pratique-t-on le 'smash', le 'lob' et le 'passing-shot' ?", a: "Le tennis", exp: "Ces termes techniques du tennis décrivent respectivement une frappe en puissance vers le bas, un lift lobé par-dessus l'adversaire au filet, et un tir passant.", diff: 1 },

  // ── HISTOIRE ───────────────────────────────────────────────────────────────
  { id: 9,  cat: 'histoire', q: "En quelle année a débuté la Révolution française ?", a: "1789", exp: "La prise de la Bastille le 14 juillet 1789 est le symbole du début de la Révolution. La Déclaration des droits de l'Homme suit le 26 août.", diff: 1 },
  { id: 10, cat: 'histoire', q: "Qui a peint le plafond de la chapelle Sixtine ?", a: "Michel-Ange (1508–1512)", exp: "Michel-Ange a peint 500 m² de fresques sur commande du pape Jules II, représentant des scènes de la Genèse dont la célèbre Création d'Adam.", diff: 1 },
  { id: 11, cat: 'histoire', q: "Quelle civilisation a construit les pyramides de Gizeh ?", a: "Les Égyptiens anciens (vers 2560–2510 av. J.-C.)", exp: "Les trois pyramides furent bâties pour les pharaons Khéops, Khéphren et Mykérinos. La grande pyramide fut la plus haute construction humaine pendant 3 800 ans.", diff: 1 },
  { id: 12, cat: 'histoire', q: "En quelle année le mur de Berlin est-il tombé ?", a: "1989 (9 novembre)", exp: "Après 28 ans de séparation, la frontière est ouverte dans la nuit du 9 au 10 novembre 1989. La réunification allemande suit le 3 octobre 1990.", diff: 1 },
  { id: 13, cat: 'histoire', q: "Quel traité a officiellement mis fin à la Première Guerre mondiale ?", a: "Le Traité de Versailles (28 juin 1919)", exp: "Signé dans la galerie des Glaces du château de Versailles, il impose de lourdes réparations à l'Allemagne, semant les graines du conflit suivant.", diff: 2 },
  { id: 14, cat: 'histoire', q: "Qui était la première femme à obtenir un prix Nobel ?", a: "Marie Curie — Nobel de Physique en 1903", exp: "Marie Curie obtiendra un second Nobel en 1911 (Chimie), devenant la première personne à en remporter deux dans des disciplines différentes.", diff: 2 },
  { id: 15, cat: 'histoire', q: "Dans quelle ville l'archiduc François-Ferdinand a-t-il été assassiné en 1914 ?", a: "Sarajevo (28 juin 1914)", exp: "L'assassinat par Gavrilo Princip déclenche la chaîne d'ultimatums menant à la Première Guerre mondiale, six semaines plus tard.", diff: 3 },
  { id: 16, cat: 'histoire', q: "Quel événement marque la fin de l'Empire romain d'Occident ?", a: "La déposition de Romulus Augustule en 476 apr. J.-C.", exp: "Odoacre, chef des Hérules, dépose le dernier empereur en 476. La date est conventionnellement retenue comme la fin de l'Antiquité.", diff: 3 },

  // ── GÉOGRAPHIE ─────────────────────────────────────────────────────────────
  { id: 17, cat: 'geo', q: "Quel est le plus long fleuve du monde ?", a: "Le Nil (6 650 km)", exp: "Selon la majorité des sources, le Nil est le plus long. Certaines études récentes mettent l'Amazone en tête selon le point de source retenu.", diff: 2 },
  { id: 18, cat: 'geo', q: "Quelle est la capitale du Canada ?", a: "Ottawa", exp: "Ottawa est la capitale fédérale depuis 1857, choisie par la reine Victoria comme compromis entre Toronto (anglophone) et Montréal (francophone).", diff: 2 },
  { id: 19, cat: 'geo', q: "Quel est le plus grand pays du monde en superficie ?", a: "La Russie (17,1 millions de km²)", exp: "La Russie couvre plus de 11 % des terres émergées et s'étend sur 11 fuseaux horaires, soit presque deux fois la superficie du Canada.", diff: 1 },
  { id: 20, cat: 'geo', q: "Quel est le plus haut sommet du monde ?", a: "L'Everest (8 849 m)", exp: "Situé dans l'Himalaya entre le Népal et le Tibet, l'Everest a été gravi pour la première fois le 29 mai 1953 par Edmund Hillary et Tenzing Norgay.", diff: 1 },
  { id: 21, cat: 'geo', q: "Dans quel océan se trouve Madagascar ?", a: "L'océan Indien", exp: "Madagascar est la 4e plus grande île du monde, à 400 km de la côte mozambicaine. Sa faune est unique : 90 % des espèces y sont endémiques.", diff: 2 },
  { id: 22, cat: 'geo', q: "Quelle est la monnaie officielle du Japon ?", a: "Le yen (¥)", exp: "Introduit en 1871 pour moderniser le système monétaire japonais, le yen est l'une des trois devises les plus échangées au monde avec le dollar et l'euro.", diff: 1 },
  { id: 23, cat: 'geo', q: "Combien de pays partagent une frontière avec la France métropolitaine ?", a: "8 pays", exp: "Belgique, Luxembourg, Allemagne, Suisse, Italie, Monaco, Andorre et Espagne. La France a la plus grande diversité de voisins en Europe de l'Ouest.", diff: 2 },
  { id: 24, cat: 'geo', q: "Quel détroit sépare l'Europe de l'Afrique ?", a: "Le détroit de Gibraltar (14 km au minimum)", exp: "Seulement 14 km séparent l'Espagne du Maroc au point le plus étroit. Le détroit relie l'Atlantique à la Méditerranée.", diff: 2 },

  // ── SCIENCE ────────────────────────────────────────────────────────────────
  { id: 25, cat: 'science', q: "Quelle est la formule chimique de l'eau ?", a: "H₂O", exp: "L'eau est composée de deux atomes d'hydrogène et d'un atome d'oxygène. Cette molécule polaire est indispensable à toute vie connue.", diff: 1 },
  { id: 26, cat: 'science', q: "Qui a développé la théorie de la relativité générale ?", a: "Albert Einstein (1915)", exp: "La relativité générale décrit la gravitation comme une courbure de l'espace-temps. Elle prédit les trous noirs, les ondes gravitationnelles et la dilatation du temps.", diff: 1 },
  { id: 27, cat: 'science', q: "Combien d'os possède le corps humain adulte ?", a: "206 os", exp: "À la naissance on en compte ~270, mais certains fusionnent. Le plus petit est l'étrier dans l'oreille (3 mm) ; le plus grand est le fémur.", diff: 2 },
  { id: 28, cat: 'science', q: "Quelle planète est surnommée la 'planète rouge' ?", a: "Mars", exp: "Mars doit sa couleur rouge à l'oxyde de fer (rouille) en surface. C'est la planète la plus susceptible d'être habitée par des humains dans le futur.", diff: 1 },
  { id: 29, cat: 'science', q: "À quelle vitesse se déplace la lumière dans le vide ?", a: "≈ 300 000 km/s (exactement 299 792 458 m/s)", exp: "C'est la vitesse maximale de l'univers. À cette vitesse, la lumière parcourt la distance Terre-Lune en 1,3 seconde et fait le tour de la Terre en 0,13 s.", diff: 2 },
  { id: 30, cat: 'science', q: "Quel élément chimique est le plus abondant dans l'univers ?", a: "L'hydrogène (H)", exp: "L'hydrogène représente ~75 % de la matière baryonique de l'univers. Il est le carburant principal des étoiles via la fusion nucléaire.", diff: 2 },
  { id: 31, cat: 'science', q: "Qu'est-ce que la photosynthèse ?", a: "La conversion de lumière + CO₂ + eau en glucose + oxygène par les plantes", exp: "La photosynthèse se déroule dans les chloroplastes. Elle est à la base de presque toutes les chaînes alimentaires terrestres.", diff: 1 },
  { id: 32, cat: 'science', q: "Quel est le symbole chimique de l'or ?", a: "Au (du latin Aurum)", exp: "L'or (numéro atomique 79) est un métal noble très conducteur, résistant à l'oxydation. Un gramme d'or peut être étiré en un fil de 165 mètres.", diff: 2 },

  // ── ART (peinture — format ticket avec œuvre) ───────────────────────────────
  { id: 33, cat: 'art', title: "La Joconde", artist: "Léonard de Vinci", year: "1503", diff: 1,
    img: "assets/art/joconde.jpg",
    exp: "Vers 1503. Le tableau le plus visité au monde, exposé au Louvre. Son sourire énigmatique et la technique du sfumato en font une icône absolue." },
  { id: 34, cat: 'art', title: "La Nuit étoilée", artist: "Vincent van Gogh", year: "1889", diff: 1,
    img: "assets/art/nuit-etoilee.jpg",
    exp: "Peinte en 1889 depuis sa chambre à l'asile de Saint-Rémy-de-Provence. Elle est aujourd'hui exposée au MoMA de New York." },
  { id: 35, cat: 'art', title: "Le Cri", artist: "Edvard Munch", year: "1893", diff: 1,
    img: "assets/art/le-cri.jpg",
    exp: "Réalisé en 1893, symbole universel de l'angoisse existentielle moderne. Munch en a peint quatre versions ; la plus célèbre est au Musée National d'Oslo." },
  { id: 36, cat: 'art', title: "La Jeune Fille à la perle", artist: "Johannes Vermeer", year: "1665", diff: 2,
    img: "assets/art/jeune-fille-perle.jpg",
    exp: "Vers 1665, surnommée la « Joconde du Nord ». Ce n'est pas un portrait mais une « tronie », une étude de visage. Conservée au Mauritshuis de La Haye." },
  { id: 37, cat: 'art', title: "La Grande Vague de Kanagawa", artist: "Katsushika Hokusai", year: "1831", diff: 2,
    img: "assets/art/grande-vague.jpg",
    exp: "Vers 1831, l'estampe japonaise (ukiyo-e) la plus célèbre. Une vague géante menace des barques devant le mont Fuji. Hokusai l'a réalisée à environ 70 ans." },
  { id: 38, cat: 'art', title: "La Naissance de Vénus", artist: "Sandro Botticelli", year: "1485", diff: 2,
    img: "assets/art/naissance-venus.jpg",
    exp: "Vers 1485, chef-d'œuvre de la Renaissance florentine. Vénus émerge des flots sur une coquille, soufflée vers le rivage par Zéphyr. Exposé aux Offices, à Florence." },
  { id: 39, cat: 'art', title: "La Liberté guidant le peuple", artist: "Eugène Delacroix", year: "1830", diff: 2,
    img: "assets/art/liberte.jpg",
    exp: "1830. Allégorie de la Liberté brandissant le drapeau tricolore sur des barricades, inspirée des Trois Glorieuses de juillet 1830. Conservée au Louvre." },
  { id: 40, cat: 'art', title: "Impression, soleil levant", artist: "Claude Monet", year: "1872", diff: 3,
    img: "assets/art/impression-soleil.jpg",
    exp: "1872. C'est cette toile qui a donné son nom à l'impressionnisme — terme d'abord employé de façon moqueuse par le critique Louis Leroy. Musée Marmottan, Paris." },
  { id: 41, cat: 'art', title: "Le Baiser", artist: "Gustav Klimt", year: "1908", diff: 2,
    img: "assets/art/le-baiser.jpg",
    exp: "1908, œuvre phare de la « période dorée » de Klimt, réalisée à la feuille d'or véritable. Symbole de l'Art nouveau viennois. Conservé au Belvédère, Vienne." },
  { id: 42, cat: 'art', title: "La Cène", artist: "Léonard de Vinci", year: "1495", diff: 2,
    img: "assets/art/la-cene.jpg",
    exp: "Vers 1495, peinture murale à Milan représentant le dernier repas du Christ avec ses apôtres. Célèbre pour sa composition en perspective et le visage de Judas." },
  { id: 43, cat: 'art', title: "Guernica", artist: "Pablo Picasso", year: "1937", diff: 2,
    img: "assets/art/guernica.jpg",
    exp: "1937. Œuvre monumentale (3,49 × 7,76 m) peinte en réponse au bombardement de la ville basque de Guernica par les nazis. Symbole universel de l'horreur de la guerre. Musée Reina Sofía, Madrid." },
  { id: 44, cat: 'art', title: "La Persistance de la mémoire", artist: "Salvador Dalí", year: "1931", diff: 2,
    img: "assets/art/montres-molles.jpg",
    exp: "1931, aussi appelée « Les Montres molles ». Huile sur toile (24 × 33 cm) peinte en quelques heures, dit Dalí, inspiré par la vision d'un camembert qui fond. MoMA, New York." },
  { id: 45, cat: 'art', title: "Les Demoiselles d'Avignon", artist: "Pablo Picasso", year: "1907", diff: 3,
    img: "assets/art/demoiselles-avignon.jpg",
    exp: "1907. Toile révolutionnaire qui brise toutes les conventions de la représentation du corps humain et pose les bases du cubisme. MoMA, New York." },
  { id: 46, cat: 'art', title: "Les Tournesols", artist: "Vincent van Gogh", year: "1888", diff: 1,
    img: "assets/art/tournesols.jpg",
    exp: "1888, série de 7 toiles peintes à Arles pour décorer la chambre de Gauguin. Symbole de l'amitié de Van Gogh. L'une d'elles a été vendue en 1987 pour 39,9 millions de dollars." },
  { id: 47, cat: 'art', title: "Les Époux Arnolfini", artist: "Jan van Eyck", year: "1434", diff: 3,
    img: "assets/art/arnolfini.jpg",
    exp: "1434. Portrait double mystérieux et extraordinairement détaillé de Giovanni di Nicolao Arnolfini et son épouse. Van Eyck se représente dans le miroir convexe en arrière-plan. National Gallery, Londres." },
  { id: 48, cat: 'art', title: "American Gothic", artist: "Grant Wood", year: "1930", diff: 2,
    img: "assets/art/american-gothic.jpg",
    exp: "1930. Icône de la peinture américaine représentant un fermier et sa fille (souvent pris pour mari et femme) devant une maison de style gothique charpentier. Art Institute of Chicago." },
  { id: 49, cat: 'art', title: "Saturne dévorant son fils", artist: "Francisco de Goya", year: "1823", diff: 3,
    img: "assets/art/saturne-goya.jpg",
    exp: "1823. L'une des 14 « Peintures noires » que Goya réalisa directement sur les murs de sa maison à la fin de sa vie. Scène terrifiante tirée de la mythologie : Saturne dévore ses enfants de peur d'être détrôné. Musée du Prado, Madrid." },
  { id: 50, cat: 'art', title: "L'École d'Athènes", artist: "Raphaël", year: "1511", diff: 3,
    img: "assets/art/ecole-athenes.jpg",
    exp: "1511. Fresque monumentale (770 cm de large) commandée par le pape Jules II pour ses appartements au Vatican. Elle réunit les plus grands philosophes de l'Antiquité : Platon (au centre) pointe vers le ciel, Aristote vers la terre. Musées du Vatican." },
  { id: 51, cat: 'art', title: "Le Radeau de la Méduse", artist: "Théodore Géricault", year: "1819", diff: 3,
    img: "assets/art/radeau-meduse.jpg",
    exp: "1819. Toile monumentale (5 × 7 m) inspirée du naufrage réel de la frégate Méduse en 1816, qui causa la mort de 147 personnes. Géricault a interviewé des survivants et peint des cadavres pour se documenter. Musée du Louvre." },
  { id: 52, cat: 'art', title: "Autoportrait au collier d'épines", artist: "Frida Kahlo", year: "1940", diff: 2,
    img: "assets/art/frida-kahlo.jpg",
    exp: "1940. L'une des œuvres les plus connues de Kahlo, peinte après son divorce d'avec Diego Rivera. Le colibri porte-bonheur, le chat noir et le singe renvoient à la symbolique mexicaine. University of Texas, Austin." },
  { id: 77, cat: 'art', title: "Les Glaneuses", artist: "Jean-François Millet", year: "1857", diff: 2,
    img: "assets/art/glaneuses.jpg",
    exp: "1857. Trois femmes ramassent les épis de blé laissés après la moisson — un travail réservé aux plus pauvres. Le tableau fut mal reçu à l'époque : les conservateurs craignaient une ode au socialisme paysan. Musée d'Orsay, Paris." },
  { id: 78, cat: 'art', title: "Olympia", artist: "Édouard Manet", year: "1863", diff: 3,
    img: "assets/art/olympia-manet.jpg",
    exp: "1863. Femme nue allongée, regardant le spectateur droit dans les yeux — scandale absolu au Salon de 1865. Manet s'inspire de la Vénus d'Urbin du Titien, mais remplace la déesse par une prostituée moderne. Musée d'Orsay, Paris." },
  { id: 79, cat: 'art', title: "La Ronde de nuit", artist: "Rembrandt van Rijn", year: "1642", diff: 2,
    img: "assets/art/ronde-nuit.jpg",
    exp: "1642. Chef-d'œuvre du baroque hollandais représentant une milice en marche, dont la composition dynamique et l'utilisation révolutionnaire de la lumière et de l'ombre sidérèrent les contemporains. Rijksmuseum, Amsterdam." },
  { id: 80, cat: 'art', title: "Les Nymphéas", artist: "Claude Monet", year: "1906", diff: 2,
    img: "assets/art/nympheas.jpg",
    exp: "1906. Série de 250 toiles peintes sur 30 ans dans le jardin de Giverny. Monet, atteint de cataractes, s'affranchit progressivement de la réalité pour aboutir à une abstraction quasi totale. Musée de l'Orangerie, Paris." },

  // ── CINÉMA ─────────────────────────────────────────────────────────────────
  { id: 53, cat: 'cinema', q: "Quel film de Steven Spielberg est le plus rentable de sa carrière ?", a: "E.T. l'extra-terrestre (1982)", exp: "E.T. a tenu le record du film le plus rentable de l'histoire pendant 11 ans, avant d'être détrôné par Jurassic Park, puis Titanic.", diff: 2 },
  { id: 54, cat: 'cinema', q: "Qui a réalisé la trilogie 'Le Seigneur des Anneaux' ?", a: "Peter Jackson (2001–2003)", exp: "Le Retour du Roi remporte 11 Oscars dont Meilleur Film, égalant Ben-Hur et Titanic. La trilogie est tournée intégralement en Nouvelle-Zélande.", diff: 1 },
  { id: 55, cat: 'cinema', q: "Dans quel film entend-on la réplique 'Je suis ton père' ?", a: "L'Empire contre-attaque (1980)", exp: "C'est Darth Vader qui la dit à Luke Skywalker. La réplique originale en anglais est 'I am your father'. Elle est considérée comme le twist le plus célèbre du cinéma.", diff: 1 },
  { id: 56, cat: 'cinema', q: "Qui a joué le rôle de James Bond pour la première fois au cinéma ?", a: "Sean Connery (Dr. No, 1962)", exp: "Connery incarne Bond dans 7 films. La franchise est la plus longue de l'histoire du cinéma, avec plus de 60 ans de production.", diff: 2 },
  { id: 57, cat: 'cinema', q: "Quel studio d'animation a créé Toy Story, Cars et Up ?", a: "Pixar Animation Studios", exp: "Toy Story (1995) est le premier long-métrage entièrement en images de synthèse. Pixar a été acquis par Disney en 2006 pour 7,4 milliards de dollars.", diff: 1 },
  { id: 58, cat: 'cinema', q: "Quel film a remporté la Palme d'Or à Cannes en 2019 ?", a: "Parasite — Bong Joon-ho (Corée du Sud)", exp: "Parasite remporte ensuite 4 Oscars en 2020 dont Meilleur Film, devenant le premier film non anglophone à obtenir cette récompense suprême.", diff: 2 },
  { id: 59, cat: 'cinema', q: "Quel réalisateur est derrière 'Pulp Fiction', 'Kill Bill' et 'Django Unchained' ?", a: "Quentin Tarantino", exp: "Tarantino est célèbre pour ses dialogues ciselés, sa violence stylisée, ses structures non-linéaires et ses nombreuses références à la culture pop.", diff: 1 },
  { id: 60, cat: 'cinema', q: "Quel film de Stanley Kubrick se déroule dans un hôtel isolé sous la neige ?", a: "Shining (The Shining, 1980)", exp: "Adapté du roman de Stephen King, Shining met en scène Jack Nicholson dans le rôle d'un écrivain devenant fou dans l'Overlook Hotel. Le film est classé #1 des films d'horreur.", diff: 2 },

  // ── CULINAIRE ──────────────────────────────────────────────────────────────
  { id: 61, cat: 'culinaire', q: "De quel pays est originaire la pizza ?", a: "L'Italie (Naples)", exp: "La pizza moderne naît à Naples au XVIIIe siècle. La Margherita fut créée en 1889 pour la reine Marguerite de Savoie, avec les couleurs du drapeau italien.", diff: 1 },
  { id: 62, cat: 'culinaire', q: "Quel est l'ingrédient principal du guacamole ?", a: "L'avocat", exp: "Le guacamole vient de l'aztèque 'ahuacamolli' (sauce d'avocat). Il est agrémenté de citron vert, d'oignon, de coriandre et de piment au Mexique.", diff: 1 },
  { id: 63, cat: 'culinaire', q: "Quelle épice est la plus chère au monde au kilo ?", a: "Le safran (jusqu'à 30 000 €/kg)", exp: "Le safran provient des stigmates de la fleur Crocus sativus. Une seule fleur ne donne que 3 stigmates ; il en faut ~200 000 pour obtenir 500 g de safran.", diff: 2 },
  { id: 64, cat: 'culinaire', q: "De quel pays est originaire le sushi ?", a: "Le Japon", exp: "Le sushi existe sous forme de poisson fermenté dans du riz depuis le IXe siècle. Le nigiri-sushi actuel apparaît à Edo (Tokyo) au début du XIXe siècle.", diff: 1 },
  { id: 65, cat: 'culinaire', q: "Quel pays produit le plus de cacao au monde ?", a: "La Côte d'Ivoire (~45 % de la production mondiale)", exp: "La Côte d'Ivoire est suivie par le Ghana et l'Indonésie. L'Afrique de l'Ouest représente à elle seule 70 % de la production mondiale de cacao.", diff: 3 },
  { id: 66, cat: 'culinaire', q: "Comment appelle-t-on un steak à peine saisi, encore froid à l'intérieur ?", a: "Bleu", exp: "L'ordre de cuisson en France : bleu → saignant → à point → bien cuit. Un steak 'bleu' est juste saisi en surface, rouge et froid au centre.", diff: 1 },
  { id: 67, cat: 'culinaire', q: "Quelle est la différence principale entre un cappuccino et un latte ?", a: "Le ratio lait/mousse : le cappuccino a plus de mousse, le latte plus de lait", exp: "Cappuccino : 1/3 espresso, 1/3 lait chaud, 1/3 mousse (environ 180 ml). Latte : même base mais 3× plus de lait chaud et très peu de mousse (250-400 ml).", diff: 2 },
  { id: 68, cat: 'culinaire', q: "Qu'est-ce que la 'réaction de Maillard' en cuisine ?", a: "La réaction chimique entre acides aminés et sucres qui dore et parfume les aliments", exp: "Décrite par Louis-Camille Maillard en 1912, cette réaction est responsable du goût et de la couleur du pain grillé, de la viande saisie, du café torréfié…", diff: 3 },

  // ── MUSIQUE ────────────────────────────────────────────────────────────────
  { id: 69, cat: 'musique', q: "Combien de cordes possède une guitare classique ?", a: "6 cordes", exp: "Accordées Mi-La-Ré-Sol-Si-Mi (de la plus grave à la plus aiguë). La guitare de 12 cordes double chaque corde pour un son plus riche.", diff: 1 },
  { id: 70, cat: 'musique', q: "Quel groupe britannique a enregistré 'Bohemian Rhapsody' ?", a: "Queen (1975)", exp: "Composée par Freddie Mercury, cette chanson de 6 minutes était révolutionnaire. Elle est restée #1 au Royaume-Uni 9 semaines, puis à nouveau après la mort de Mercury en 1991.", diff: 1 },
  { id: 71, cat: 'musique', q: "Quel chanteur français est surnommé 'La Môme' ?", a: "Édith Piaf", exp: "Édith Piaf (1915-1963) mesure 1,47 m — d'où son surnom 'La Môme Piaf' (petit moineau). Elle est notamment connue pour 'La Vie en rose' et 'Non, je ne regrette rien'.", diff: 1 },
  { id: 72, cat: 'musique', q: "Dans quel pays est né le reggae ?", a: "La Jamaïque (fin des années 1960)", exp: "Le reggae émerge en Jamaïque à la fin des années 60, popularisé internationalement par Bob Marley. Il est influencé par le ska et le rocksteady.", diff: 1 },
  { id: 73, cat: 'musique', q: "Qui est le compositeur de 'La Flûte enchantée' ?", a: "Wolfgang Amadeus Mozart (1791)", exp: "La Flûte enchantée est le dernier opéra de Mozart, composé quelques mois avant sa mort. C'est l'opéra le plus joué en Allemagne et l'un des plus joués au monde.", diff: 2 },
  { id: 74, cat: 'musique', q: "Quel album des Beatles est souvent classé meilleur album de tous les temps ?", a: "Sgt. Pepper's Lonely Hearts Club Band (1967)", exp: "Régulièrement n°1 dans les classements critiques, cet album introduit des techniques d'enregistrement révolutionnaires et le concept d'album cohérent comme œuvre d'art.", diff: 2 },
  { id: 75, cat: 'musique', q: "Qui a composé les 'Quatre Saisons' ?", a: "Antonio Vivaldi (vers 1720)", exp: "Les Quatre Saisons sont 4 concertos pour violon composés par Vivaldi. Chaque concerto décrit musicalement une saison, accompagné d'un sonnet explicatif.", diff: 2 },
  { id: 76, cat: 'musique', q: "Quel genre musical est né à Chicago et Detroit dans les années 1980 ?", a: "La house et la techno", exp: "La house naît à Chicago (DJ Frankie Knuckles au Warehouse) et la techno à Detroit (Juan Atkins, Derrick May, Kevin Saunderson). Deux piliers de la musique électronique mondiale.", diff: 3 },
];
